//go:build !ignore_autogenerated

// Copyright 2026 Bitwise Media Group Ltd.
// SPDX-License-Identifier: MIT

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSConfigAggregator) DeepCopyInto(out *AWSConfigAggregator) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSConfigAggregator.
func (in *AWSConfigAggregator) DeepCopy() *AWSConfigAggregator {
	if in == nil {
		return nil
	}
	out := new(AWSConfigAggregator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSIntegration) DeepCopyInto(out *AWSIntegration) {
	*out = *in
	if in.ResourceTags != nil {
		in, out := &in.ResourceTags, &out.ResourceTags
		*out = new(AWSResourceTags)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSIntegration.
func (in *AWSIntegration) DeepCopy() *AWSIntegration {
	if in == nil {
		return nil
	}
	out := new(AWSIntegration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSResourceExplorer) DeepCopyInto(out *AWSResourceExplorer) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSResourceExplorer.
func (in *AWSResourceExplorer) DeepCopy() *AWSResourceExplorer {
	if in == nil {
		return nil
	}
	out := new(AWSResourceExplorer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSResourceTags) DeepCopyInto(out *AWSResourceTags) {
	*out = *in
	if in.ConfigAggregator != nil {
		in, out := &in.ConfigAggregator, &out.ConfigAggregator
		*out = new(AWSConfigAggregator)
		**out = **in
	}
	if in.ResourceExplorer != nil {
		in, out := &in.ResourceExplorer, &out.ResourceExplorer
		*out = new(AWSResourceExplorer)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = new(AssetLabelKeys)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSResourceTags.
func (in *AWSResourceTags) DeepCopy() *AWSResourceTags {
	if in == nil {
		return nil
	}
	out := new(AWSResourceTags)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionRequest) DeepCopyInto(out *ActionRequest) {
	*out = *in
	in.At.DeepCopyInto(&out.At)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionRequest.
func (in *ActionRequest) DeepCopy() *ActionRequest {
	if in == nil {
		return nil
	}
	out := new(ActionRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActiveRun) DeepCopyInto(out *ActiveRun) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActiveRun.
func (in *ActiveRun) DeepCopy() *ActiveRun {
	if in == nil {
		return nil
	}
	out := new(ActiveRun)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentEstimate) DeepCopyInto(out *AgentEstimate) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentEstimate.
func (in *AgentEstimate) DeepCopy() *AgentEstimate {
	if in == nil {
		return nil
	}
	out := new(AgentEstimate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentParameters) DeepCopyInto(out *AgentParameters) {
	*out = *in
	if in.Estimate != nil {
		in, out := &in.Estimate, &out.Estimate
		*out = new(AgentEstimate)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentParameters.
func (in *AgentParameters) DeepCopy() *AgentParameters {
	if in == nil {
		return nil
	}
	out := new(AgentParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Alert) DeepCopyInto(out *Alert) {
	*out = *in
	if in.Locations != nil {
		in, out := &in.Locations, &out.Locations
		*out = make([]Location, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Alert.
func (in *Alert) DeepCopy() *Alert {
	if in == nil {
		return nil
	}
	out := new(Alert)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Analysis) DeepCopyInto(out *Analysis) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Analysis.
func (in *Analysis) DeepCopy() *Analysis {
	if in == nil {
		return nil
	}
	out := new(Analysis)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Approval) DeepCopyInto(out *Approval) {
	*out = *in
	in.At.DeepCopyInto(&out.At)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Approval.
func (in *Approval) DeepCopy() *Approval {
	if in == nil {
		return nil
	}
	out := new(Approval)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Artifact) DeepCopyInto(out *Artifact) {
	*out = *in
	if in.LastFetchedAt != nil {
		in, out := &in.LastFetchedAt, &out.LastFetchedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Artifact.
func (in *Artifact) DeepCopy() *Artifact {
	if in == nil {
		return nil
	}
	out := new(Artifact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssetLabelKeys) DeepCopyInto(out *AssetLabelKeys) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssetLabelKeys.
func (in *AssetLabelKeys) DeepCopy() *AssetLabelKeys {
	if in == nil {
		return nil
	}
	out := new(AssetLabelKeys)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttemptCounts) DeepCopyInto(out *AttemptCounts) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttemptCounts.
func (in *AttemptCounts) DeepCopy() *AttemptCounts {
	if in == nil {
		return nil
	}
	out := new(AttemptCounts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureIntegration) DeepCopyInto(out *AzureIntegration) {
	*out = *in
	if in.ResourceTags != nil {
		in, out := &in.ResourceTags, &out.ResourceTags
		*out = new(AzureResourceTags)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureIntegration.
func (in *AzureIntegration) DeepCopy() *AzureIntegration {
	if in == nil {
		return nil
	}
	out := new(AzureIntegration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureResourceTags) DeepCopyInto(out *AzureResourceTags) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = new(AssetLabelKeys)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureResourceTags.
func (in *AzureResourceTags) DeepCopy() *AzureResourceTags {
	if in == nil {
		return nil
	}
	out := new(AzureResourceTags)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackfillRequest) DeepCopyInto(out *BackfillRequest) {
	*out = *in
	in.At.DeepCopyInto(&out.At)
	if in.Repositories != nil {
		in, out := &in.Repositories, &out.Repositories
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackfillRequest.
func (in *BackfillRequest) DeepCopy() *BackfillRequest {
	if in == nil {
		return nil
	}
	out := new(BackfillRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackfillStatus) DeepCopyInto(out *BackfillStatus) {
	*out = *in
	if in.LastRunAt != nil {
		in, out := &in.LastRunAt, &out.LastRunAt
		*out = (*in).DeepCopy()
	}
	if in.BackfilledAt != nil {
		in, out := &in.BackfilledAt, &out.BackfilledAt
		*out = (*in).DeepCopy()
	}
	if in.AttemptedAt != nil {
		in, out := &in.AttemptedAt, &out.AttemptedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackfillStatus.
func (in *BackfillStatus) DeepCopy() *BackfillStatus {
	if in == nil {
		return nil
	}
	out := new(BackfillStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CaseSummary) DeepCopyInto(out *CaseSummary) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CaseSummary.
func (in *CaseSummary) DeepCopy() *CaseSummary {
	if in == nil {
		return nil
	}
	out := new(CaseSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommandActor) DeepCopyInto(out *CommandActor) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommandActor.
func (in *CommandActor) DeepCopy() *CommandActor {
	if in == nil {
		return nil
	}
	out := new(CommandActor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Enrichment) DeepCopyInto(out *Enrichment) {
	*out = *in
	if in.Owners != nil {
		in, out := &in.Owners, &out.Owners
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.AppliedAt.DeepCopyInto(&out.AppliedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Enrichment.
func (in *Enrichment) DeepCopy() *Enrichment {
	if in == nil {
		return nil
	}
	out := new(Enrichment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EstimateAggregate) DeepCopyInto(out *EstimateAggregate) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EstimateAggregate.
func (in *EstimateAggregate) DeepCopy() *EstimateAggregate {
	if in == nil {
		return nil
	}
	out := new(EstimateAggregate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Evaluation) DeepCopyInto(out *Evaluation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Evaluation.
func (in *Evaluation) DeepCopy() *Evaluation {
	if in == nil {
		return nil
	}
	out := new(Evaluation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Evaluation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvaluationList) DeepCopyInto(out *EvaluationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Evaluation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvaluationList.
func (in *EvaluationList) DeepCopy() *EvaluationList {
	if in == nil {
		return nil
	}
	out := new(EvaluationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EvaluationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvaluationSpec) DeepCopyInto(out *EvaluationSpec) {
	*out = *in
	if in.Units != nil {
		in, out := &in.Units, &out.Units
		*out = make([]UnitPlan, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TTLSecondsAfterFinished != nil {
		in, out := &in.TTLSecondsAfterFinished, &out.TTLSecondsAfterFinished
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvaluationSpec.
func (in *EvaluationSpec) DeepCopy() *EvaluationSpec {
	if in == nil {
		return nil
	}
	out := new(EvaluationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvaluationStatus) DeepCopyInto(out *EvaluationStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvaluationStatus.
func (in *EvaluationStatus) DeepCopy() *EvaluationStatus {
	if in == nil {
		return nil
	}
	out := new(EvaluationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvaluationUnit) DeepCopyInto(out *EvaluationUnit) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvaluationUnit.
func (in *EvaluationUnit) DeepCopy() *EvaluationUnit {
	if in == nil {
		return nil
	}
	out := new(EvaluationUnit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EvaluationUnit) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvaluationUnitList) DeepCopyInto(out *EvaluationUnitList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EvaluationUnit, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvaluationUnitList.
func (in *EvaluationUnitList) DeepCopy() *EvaluationUnitList {
	if in == nil {
		return nil
	}
	out := new(EvaluationUnitList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EvaluationUnitList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvaluationUnitSpec) DeepCopyInto(out *EvaluationUnitSpec) {
	*out = *in
	out.EvaluationRef = in.EvaluationRef
	in.Unit.DeepCopyInto(&out.Unit)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvaluationUnitSpec.
func (in *EvaluationUnitSpec) DeepCopy() *EvaluationUnitSpec {
	if in == nil {
		return nil
	}
	out := new(EvaluationUnitSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvaluationUnitStatus) DeepCopyInto(out *EvaluationUnitStatus) {
	*out = *in
	if in.JobRef != nil {
		in, out := &in.JobRef, &out.JobRef
		*out = new(JobReference)
		**out = **in
	}
	if in.Cases != nil {
		in, out := &in.Cases, &out.Cases
		*out = make([]CaseSummary, len(*in))
		copy(*out, *in)
	}
	out.Usage = in.Usage
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.FinishedAt != nil {
		in, out := &in.FinishedAt, &out.FinishedAt
		*out = (*in).DeepCopy()
	}
	if in.ResultsRef != nil {
		in, out := &in.ResultsRef, &out.ResultsRef
		*out = new(TranscriptRef)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvaluationUnitStatus.
func (in *EvaluationUnitStatus) DeepCopy() *EvaluationUnitStatus {
	if in == nil {
		return nil
	}
	out := new(EvaluationUnitStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Finding) DeepCopyInto(out *Finding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Finding.
func (in *Finding) DeepCopy() *Finding {
	if in == nil {
		return nil
	}
	out := new(Finding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Finding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FindingCloudResource) DeepCopyInto(out *FindingCloudResource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FindingCloudResource.
func (in *FindingCloudResource) DeepCopy() *FindingCloudResource {
	if in == nil {
		return nil
	}
	out := new(FindingCloudResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FindingCommand) DeepCopyInto(out *FindingCommand) {
	*out = *in
	out.Actor = in.Actor
	in.ReceivedAt.DeepCopyInto(&out.ReceivedAt)
	if in.DecidedAt != nil {
		in, out := &in.DecidedAt, &out.DecidedAt
		*out = (*in).DeepCopy()
	}
	if in.Available != nil {
		in, out := &in.Available, &out.Available
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AnsweringSince != nil {
		in, out := &in.AnsweringSince, &out.AnsweringSince
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FindingCommand.
func (in *FindingCommand) DeepCopy() *FindingCommand {
	if in == nil {
		return nil
	}
	out := new(FindingCommand)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FindingCommands) DeepCopyInto(out *FindingCommands) {
	*out = *in
	if in.Pending != nil {
		in, out := &in.Pending, &out.Pending
		*out = make([]FindingCommand, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Consumed != nil {
		in, out := &in.Consumed, &out.Consumed
		*out = make([]int64, len(*in))
		copy(*out, *in)
	}
	if in.RefusedActors != nil {
		in, out := &in.RefusedActors, &out.RefusedActors
		*out = make([]int64, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FindingCommands.
func (in *FindingCommands) DeepCopy() *FindingCommands {
	if in == nil {
		return nil
	}
	out := new(FindingCommands)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FindingList) DeepCopyInto(out *FindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Finding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FindingList.
func (in *FindingList) DeepCopy() *FindingList {
	if in == nil {
		return nil
	}
	out := new(FindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FindingRepository) DeepCopyInto(out *FindingRepository) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FindingRepository.
func (in *FindingRepository) DeepCopy() *FindingRepository {
	if in == nil {
		return nil
	}
	out := new(FindingRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FindingRollup) DeepCopyInto(out *FindingRollup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FindingRollup.
func (in *FindingRollup) DeepCopy() *FindingRollup {
	if in == nil {
		return nil
	}
	out := new(FindingRollup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FindingRollup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FindingRollupList) DeepCopyInto(out *FindingRollupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FindingRollup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FindingRollupList.
func (in *FindingRollupList) DeepCopy() *FindingRollupList {
	if in == nil {
		return nil
	}
	out := new(FindingRollupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FindingRollupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FindingRollupSpec) DeepCopyInto(out *FindingRollupSpec) {
	*out = *in
	out.Scope = in.Scope
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FindingRollupSpec.
func (in *FindingRollupSpec) DeepCopy() *FindingRollupSpec {
	if in == nil {
		return nil
	}
	out := new(FindingRollupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FindingRollupStatus) DeepCopyInto(out *FindingRollupStatus) {
	*out = *in
	if in.FirstProcessed != nil {
		in, out := &in.FirstProcessed, &out.FirstProcessed
		*out = (*in).DeepCopy()
	}
	if in.LastProcessed != nil {
		in, out := &in.LastProcessed, &out.LastProcessed
		*out = (*in).DeepCopy()
	}
	in.Bucket.DeepCopyInto(&out.Bucket)
	if in.Monthly != nil {
		in, out := &in.Monthly, &out.Monthly
		*out = make(map[string]MonthlyBucket, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Recent != nil {
		in, out := &in.Recent, &out.Recent
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FindingRollupStatus.
func (in *FindingRollupStatus) DeepCopy() *FindingRollupStatus {
	if in == nil {
		return nil
	}
	out := new(FindingRollupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FindingSpec) DeepCopyInto(out *FindingSpec) {
	*out = *in
	out.IntegrationRef = in.IntegrationRef
	if in.TrackingRef != nil {
		in, out := &in.TrackingRef, &out.TrackingRef
		*out = new(LocalObjectReference)
		**out = **in
	}
	if in.Repository != nil {
		in, out := &in.Repository, &out.Repository
		*out = new(FindingRepository)
		**out = **in
	}
	if in.CloudResource != nil {
		in, out := &in.CloudResource, &out.CloudResource
		*out = new(FindingCloudResource)
		**out = **in
	}
	if in.Advisories != nil {
		in, out := &in.Advisories, &out.Advisories
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Alerts != nil {
		in, out := &in.Alerts, &out.Alerts
		*out = make([]Alert, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Related != nil {
		in, out := &in.Related, &out.Related
		*out = make([]RelatedFinding, len(*in))
		copy(*out, *in)
	}
	if in.Approval != nil {
		in, out := &in.Approval, &out.Approval
		*out = new(Approval)
		(*in).DeepCopyInto(*out)
	}
	if in.Retry != nil {
		in, out := &in.Retry, &out.Retry
		*out = new(ActionRequest)
		(*in).DeepCopyInto(*out)
	}
	if in.Expedite != nil {
		in, out := &in.Expedite, &out.Expedite
		*out = new(ActionRequest)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FindingSpec.
func (in *FindingSpec) DeepCopy() *FindingSpec {
	if in == nil {
		return nil
	}
	out := new(FindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FindingStatus) DeepCopyInto(out *FindingStatus) {
	*out = *in
	if in.PhaseTimes != nil {
		in, out := &in.PhaseTimes, &out.PhaseTimes
		*out = make([]PhaseTime, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FirstObservedAt != nil {
		in, out := &in.FirstObservedAt, &out.FirstObservedAt
		*out = (*in).DeepCopy()
	}
	if in.AccumulateUntil != nil {
		in, out := &in.AccumulateUntil, &out.AccumulateUntil
		*out = (*in).DeepCopy()
	}
	if in.Tracking != nil {
		in, out := &in.Tracking, &out.Tracking
		*out = new(TrackingStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Owners != nil {
		in, out := &in.Owners, &out.Owners
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Enrichments != nil {
		in, out := &in.Enrichments, &out.Enrichments
		*out = make([]Enrichment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Investigation != nil {
		in, out := &in.Investigation, &out.Investigation
		*out = new(InvestigationSummary)
		(*in).DeepCopyInto(*out)
	}
	if in.Remediation != nil {
		in, out := &in.Remediation, &out.Remediation
		*out = new(RemediationSummary)
		(*in).DeepCopyInto(*out)
	}
	if in.PullRequest != nil {
		in, out := &in.PullRequest, &out.PullRequest
		*out = new(PullRequestStatus)
		(*in).DeepCopyInto(*out)
	}
	out.Attempts = in.Attempts
	if in.ActiveRun != nil {
		in, out := &in.ActiveRun, &out.ActiveRun
		*out = new(ActiveRun)
		**out = **in
	}
	if in.Forge != nil {
		in, out := &in.Forge, &out.Forge
		*out = new(LocalObjectReference)
		**out = **in
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.StaleObservations != nil {
		in, out := &in.StaleObservations, &out.StaleObservations
		*out = make([]StaleObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Commands != nil {
		in, out := &in.Commands, &out.Commands
		*out = new(FindingCommands)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FindingStatus.
func (in *FindingStatus) DeepCopy() *FindingStatus {
	if in == nil {
		return nil
	}
	out := new(FindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Forge) DeepCopyInto(out *Forge) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Forge.
func (in *Forge) DeepCopy() *Forge {
	if in == nil {
		return nil
	}
	out := new(Forge)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Forge) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ForgeList) DeepCopyInto(out *ForgeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Forge, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ForgeList.
func (in *ForgeList) DeepCopy() *ForgeList {
	if in == nil {
		return nil
	}
	out := new(ForgeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ForgeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ForgeSpec) DeepCopyInto(out *ForgeSpec) {
	*out = *in
	if in.Proxy != nil {
		in, out := &in.Proxy, &out.Proxy
		*out = new(ProxyConfig)
		**out = **in
	}
	out.SecretRef = in.SecretRef
	if in.Orgs != nil {
		in, out := &in.Orgs, &out.Orgs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Repositories != nil {
		in, out := &in.Repositories, &out.Repositories
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Interval = in.Interval
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ForgeSpec.
func (in *ForgeSpec) DeepCopy() *ForgeSpec {
	if in == nil {
		return nil
	}
	out := new(ForgeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ForgeStatus) DeepCopyInto(out *ForgeStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Installations != nil {
		in, out := &in.Installations, &out.Installations
		*out = make([]InstallationSummary, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ForgeStatus.
func (in *ForgeStatus) DeepCopy() *ForgeStatus {
	if in == nil {
		return nil
	}
	out := new(ForgeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenericEnhancer) DeepCopyInto(out *GenericEnhancer) {
	*out = *in
	out.Timeout = in.Timeout
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenericEnhancer.
func (in *GenericEnhancer) DeepCopy() *GenericEnhancer {
	if in == nil {
		return nil
	}
	out := new(GenericEnhancer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenericIntegration) DeepCopyInto(out *GenericIntegration) {
	*out = *in
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(GenericSource)
		(*in).DeepCopyInto(*out)
	}
	if in.Enhance != nil {
		in, out := &in.Enhance, &out.Enhance
		*out = new(GenericEnhancer)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenericIntegration.
func (in *GenericIntegration) DeepCopy() *GenericIntegration {
	if in == nil {
		return nil
	}
	out := new(GenericIntegration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenericResolver) DeepCopyInto(out *GenericResolver) {
	*out = *in
	out.Timeout = in.Timeout
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenericResolver.
func (in *GenericResolver) DeepCopy() *GenericResolver {
	if in == nil {
		return nil
	}
	out := new(GenericResolver)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenericSource) DeepCopyInto(out *GenericSource) {
	*out = *in
	if in.Resolver != nil {
		in, out := &in.Resolver, &out.Resolver
		*out = new(GenericResolver)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenericSource.
func (in *GenericSource) DeepCopy() *GenericSource {
	if in == nil {
		return nil
	}
	out := new(GenericSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubCodeScanningAlerts) DeepCopyInto(out *GitHubCodeScanningAlerts) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubCodeScanningAlerts.
func (in *GitHubCodeScanningAlerts) DeepCopy() *GitHubCodeScanningAlerts {
	if in == nil {
		return nil
	}
	out := new(GitHubCodeScanningAlerts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubIntegration) DeepCopyInto(out *GitHubIntegration) {
	*out = *in
	if in.Proxy != nil {
		in, out := &in.Proxy, &out.Proxy
		*out = new(ProxyConfig)
		**out = **in
	}
	if in.Issues != nil {
		in, out := &in.Issues, &out.Issues
		*out = new(GitHubIssues)
		**out = **in
	}
	if in.CodeScanningAlerts != nil {
		in, out := &in.CodeScanningAlerts, &out.CodeScanningAlerts
		*out = new(GitHubCodeScanningAlerts)
		**out = **in
	}
	if in.Redelivery != nil {
		in, out := &in.Redelivery, &out.Redelivery
		*out = new(GitHubRedelivery)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubIntegration.
func (in *GitHubIntegration) DeepCopy() *GitHubIntegration {
	if in == nil {
		return nil
	}
	out := new(GitHubIntegration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubIssues) DeepCopyInto(out *GitHubIssues) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubIssues.
func (in *GitHubIssues) DeepCopy() *GitHubIssues {
	if in == nil {
		return nil
	}
	out := new(GitHubIssues)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubRedelivery) DeepCopyInto(out *GitHubRedelivery) {
	*out = *in
	out.Lookback = in.Lookback
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubRedelivery.
func (in *GitHubRedelivery) DeepCopy() *GitHubRedelivery {
	if in == nil {
		return nil
	}
	out := new(GitHubRedelivery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GoogleCloudAssetInventory) DeepCopyInto(out *GoogleCloudAssetInventory) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = new(AssetLabelKeys)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GoogleCloudAssetInventory.
func (in *GoogleCloudAssetInventory) DeepCopy() *GoogleCloudAssetInventory {
	if in == nil {
		return nil
	}
	out := new(GoogleCloudAssetInventory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GoogleCloudIntegration) DeepCopyInto(out *GoogleCloudIntegration) {
	*out = *in
	if in.SecurityCommandCenter != nil {
		in, out := &in.SecurityCommandCenter, &out.SecurityCommandCenter
		*out = new(GoogleCloudSCC)
		(*in).DeepCopyInto(*out)
	}
	if in.CloudAssetInventory != nil {
		in, out := &in.CloudAssetInventory, &out.CloudAssetInventory
		*out = new(GoogleCloudAssetInventory)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GoogleCloudIntegration.
func (in *GoogleCloudIntegration) DeepCopy() *GoogleCloudIntegration {
	if in == nil {
		return nil
	}
	out := new(GoogleCloudIntegration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GoogleCloudSCC) DeepCopyInto(out *GoogleCloudSCC) {
	*out = *in
	if in.Mute != nil {
		in, out := &in.Mute, &out.Mute
		*out = new(GoogleCloudSCCMute)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GoogleCloudSCC.
func (in *GoogleCloudSCC) DeepCopy() *GoogleCloudSCC {
	if in == nil {
		return nil
	}
	out := new(GoogleCloudSCC)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GoogleCloudSCCMute) DeepCopyInto(out *GoogleCloudSCCMute) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GoogleCloudSCCMute.
func (in *GoogleCloudSCCMute) DeepCopy() *GoogleCloudSCCMute {
	if in == nil {
		return nil
	}
	out := new(GoogleCloudSCCMute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarnessOption) DeepCopyInto(out *HarnessOption) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarnessOption.
func (in *HarnessOption) DeepCopy() *HarnessOption {
	if in == nil {
		return nil
	}
	out := new(HarnessOption)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstallationSummary) DeepCopyInto(out *InstallationSummary) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstallationSummary.
func (in *InstallationSummary) DeepCopy() *InstallationSummary {
	if in == nil {
		return nil
	}
	out := new(InstallationSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Integration) DeepCopyInto(out *Integration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Integration.
func (in *Integration) DeepCopy() *Integration {
	if in == nil {
		return nil
	}
	out := new(Integration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Integration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntegrationList) DeepCopyInto(out *IntegrationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Integration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntegrationList.
func (in *IntegrationList) DeepCopy() *IntegrationList {
	if in == nil {
		return nil
	}
	out := new(IntegrationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IntegrationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntegrationSpec) DeepCopyInto(out *IntegrationSpec) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(LocalSecretReference)
		**out = **in
	}
	out.Interval = in.Interval
	if in.Replay != nil {
		in, out := &in.Replay, &out.Replay
		*out = new(ActionRequest)
		(*in).DeepCopyInto(*out)
	}
	if in.Reset != nil {
		in, out := &in.Reset, &out.Reset
		*out = new(ActionRequest)
		(*in).DeepCopyInto(*out)
	}
	if in.Backfill != nil {
		in, out := &in.Backfill, &out.Backfill
		*out = new(BackfillRequest)
		(*in).DeepCopyInto(*out)
	}
	if in.GitHub != nil {
		in, out := &in.GitHub, &out.GitHub
		*out = new(GitHubIntegration)
		(*in).DeepCopyInto(*out)
	}
	if in.GoogleCloud != nil {
		in, out := &in.GoogleCloud, &out.GoogleCloud
		*out = new(GoogleCloudIntegration)
		(*in).DeepCopyInto(*out)
	}
	if in.Wiz != nil {
		in, out := &in.Wiz, &out.Wiz
		*out = new(WizIntegration)
		(*in).DeepCopyInto(*out)
	}
	if in.AWS != nil {
		in, out := &in.AWS, &out.AWS
		*out = new(AWSIntegration)
		(*in).DeepCopyInto(*out)
	}
	if in.Azure != nil {
		in, out := &in.Azure, &out.Azure
		*out = new(AzureIntegration)
		(*in).DeepCopyInto(*out)
	}
	if in.Generic != nil {
		in, out := &in.Generic, &out.Generic
		*out = new(GenericIntegration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntegrationSpec.
func (in *IntegrationSpec) DeepCopy() *IntegrationSpec {
	if in == nil {
		return nil
	}
	out := new(IntegrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntegrationStatus) DeepCopyInto(out *IntegrationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Installations != nil {
		in, out := &in.Installations, &out.Installations
		*out = make([]InstallationSummary, len(*in))
		copy(*out, *in)
	}
	if in.LastEventAt != nil {
		in, out := &in.LastEventAt, &out.LastEventAt
		*out = (*in).DeepCopy()
	}
	if in.RateLimit != nil {
		in, out := &in.RateLimit, &out.RateLimit
		*out = new(RateLimitStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Redelivery != nil {
		in, out := &in.Redelivery, &out.Redelivery
		*out = new(RedeliveryStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Backfill != nil {
		in, out := &in.Backfill, &out.Backfill
		*out = new(BackfillStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.ResetAt != nil {
		in, out := &in.ResetAt, &out.ResetAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntegrationStatus.
func (in *IntegrationStatus) DeepCopy() *IntegrationStatus {
	if in == nil {
		return nil
	}
	out := new(IntegrationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Intent) DeepCopyInto(out *Intent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Intent.
func (in *Intent) DeepCopy() *Intent {
	if in == nil {
		return nil
	}
	out := new(Intent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Intent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntentAction) DeepCopyInto(out *IntentAction) {
	*out = *in
	in.At.DeepCopyInto(&out.At)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntentAction.
func (in *IntentAction) DeepCopy() *IntentAction {
	if in == nil {
		return nil
	}
	out := new(IntentAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntentApproval) DeepCopyInto(out *IntentApproval) {
	*out = *in
	in.At.DeepCopyInto(&out.At)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntentApproval.
func (in *IntentApproval) DeepCopy() *IntentApproval {
	if in == nil {
		return nil
	}
	out := new(IntentApproval)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntentInput) DeepCopyInto(out *IntentInput) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntentInput.
func (in *IntentInput) DeepCopy() *IntentInput {
	if in == nil {
		return nil
	}
	out := new(IntentInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntentIssue) DeepCopyInto(out *IntentIssue) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntentIssue.
func (in *IntentIssue) DeepCopy() *IntentIssue {
	if in == nil {
		return nil
	}
	out := new(IntentIssue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntentList) DeepCopyInto(out *IntentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Intent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntentList.
func (in *IntentList) DeepCopy() *IntentList {
	if in == nil {
		return nil
	}
	out := new(IntentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IntentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntentPhaseTime) DeepCopyInto(out *IntentPhaseTime) {
	*out = *in
	in.At.DeepCopyInto(&out.At)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntentPhaseTime.
func (in *IntentPhaseTime) DeepCopy() *IntentPhaseTime {
	if in == nil {
		return nil
	}
	out := new(IntentPhaseTime)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntentPlan) DeepCopyInto(out *IntentPlan) {
	*out = *in
	if in.PostedAt != nil {
		in, out := &in.PostedAt, &out.PostedAt
		*out = (*in).DeepCopy()
	}
	if in.Repositories != nil {
		in, out := &in.Repositories, &out.Repositories
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntentPlan.
func (in *IntentPlan) DeepCopy() *IntentPlan {
	if in == nil {
		return nil
	}
	out := new(IntentPlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntentPullRequest) DeepCopyInto(out *IntentPullRequest) {
	*out = *in
	if in.MergedAt != nil {
		in, out := &in.MergedAt, &out.MergedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntentPullRequest.
func (in *IntentPullRequest) DeepCopy() *IntentPullRequest {
	if in == nil {
		return nil
	}
	out := new(IntentPullRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntentRequest) DeepCopyInto(out *IntentRequest) {
	*out = *in
	in.At.DeepCopyInto(&out.At)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntentRequest.
func (in *IntentRequest) DeepCopy() *IntentRequest {
	if in == nil {
		return nil
	}
	out := new(IntentRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntentRun) DeepCopyInto(out *IntentRun) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntentRun.
func (in *IntentRun) DeepCopy() *IntentRun {
	if in == nil {
		return nil
	}
	out := new(IntentRun)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IntentRun) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntentRunGrant) DeepCopyInto(out *IntentRunGrant) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntentRunGrant.
func (in *IntentRunGrant) DeepCopy() *IntentRunGrant {
	if in == nil {
		return nil
	}
	out := new(IntentRunGrant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntentRunInputs) DeepCopyInto(out *IntentRunInputs) {
	*out = *in
	if in.ReviewIDs != nil {
		in, out := &in.ReviewIDs, &out.ReviewIDs
		*out = make([]int64, len(*in))
		copy(*out, *in)
	}
	if in.CheckRunIDs != nil {
		in, out := &in.CheckRunIDs, &out.CheckRunIDs
		*out = make([]int64, len(*in))
		copy(*out, *in)
	}
	if in.StatusIDs != nil {
		in, out := &in.StatusIDs, &out.StatusIDs
		*out = make([]int64, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntentRunInputs.
func (in *IntentRunInputs) DeepCopy() *IntentRunInputs {
	if in == nil {
		return nil
	}
	out := new(IntentRunInputs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntentRunList) DeepCopyInto(out *IntentRunList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IntentRun, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntentRunList.
func (in *IntentRunList) DeepCopy() *IntentRunList {
	if in == nil {
		return nil
	}
	out := new(IntentRunList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IntentRunList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntentRunRepository) DeepCopyInto(out *IntentRunRepository) {
	*out = *in
	out.RepositoryRef = in.RepositoryRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntentRunRepository.
func (in *IntentRunRepository) DeepCopy() *IntentRunRepository {
	if in == nil {
		return nil
	}
	out := new(IntentRunRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntentRunSpec) DeepCopyInto(out *IntentRunSpec) {
	*out = *in
	out.IntentRef = in.IntentRef
	out.Repository = in.Repository
	in.Inputs.DeepCopyInto(&out.Inputs)
	if in.ImageFrom != nil {
		in, out := &in.ImageFrom, &out.ImageFrom
		*out = new(ObjectReference)
		**out = **in
	}
	out.Grant = in.Grant
	if in.PreviousAttempt != nil {
		in, out := &in.PreviousAttempt, &out.PreviousAttempt
		*out = new(PreviousAttempt)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntentRunSpec.
func (in *IntentRunSpec) DeepCopy() *IntentRunSpec {
	if in == nil {
		return nil
	}
	out := new(IntentRunSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntentRunStatus) DeepCopyInto(out *IntentRunStatus) {
	*out = *in
	if in.JobRef != nil {
		in, out := &in.JobRef, &out.JobRef
		*out = new(JobReference)
		**out = **in
	}
	if in.RunnerImage != nil {
		in, out := &in.RunnerImage, &out.RunnerImage
		*out = new(RunnerImageRef)
		**out = **in
	}
	out.Usage = in.Usage
	if in.Transcript != nil {
		in, out := &in.Transcript, &out.Transcript
		*out = new(TranscriptRef)
		**out = **in
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.FinishedAt != nil {
		in, out := &in.FinishedAt, &out.FinishedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntentRunStatus.
func (in *IntentRunStatus) DeepCopy() *IntentRunStatus {
	if in == nil {
		return nil
	}
	out := new(IntentRunStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntentSpec) DeepCopyInto(out *IntentSpec) {
	*out = *in
	out.Issue = in.Issue
	in.RequestedBy.DeepCopyInto(&out.RequestedBy)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntentSpec.
func (in *IntentSpec) DeepCopy() *IntentSpec {
	if in == nil {
		return nil
	}
	out := new(IntentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntentStatus) DeepCopyInto(out *IntentStatus) {
	*out = *in
	if in.PhaseTimes != nil {
		in, out := &in.PhaseTimes, &out.PhaseTimes
		*out = make([]IntentPhaseTime, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Input != nil {
		in, out := &in.Input, &out.Input
		*out = new(IntentInput)
		**out = **in
	}
	if in.Plan != nil {
		in, out := &in.Plan, &out.Plan
		*out = new(IntentPlan)
		(*in).DeepCopyInto(*out)
	}
	if in.Approval != nil {
		in, out := &in.Approval, &out.Approval
		*out = new(IntentApproval)
		(*in).DeepCopyInto(*out)
	}
	if in.LastTrigger != nil {
		in, out := &in.LastTrigger, &out.LastTrigger
		*out = new(IntentAction)
		(*in).DeepCopyInto(*out)
	}
	if in.PullRequests != nil {
		in, out := &in.PullRequests, &out.PullRequests
		*out = make([]IntentPullRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Usage = in.Usage
	if in.Tracking != nil {
		in, out := &in.Tracking, &out.Tracking
		*out = new(IntentTracking)
		**out = **in
	}
	if in.ActiveRun != nil {
		in, out := &in.ActiveRun, &out.ActiveRun
		*out = new(ObjectReference)
		**out = **in
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntentStatus.
func (in *IntentStatus) DeepCopy() *IntentStatus {
	if in == nil {
		return nil
	}
	out := new(IntentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntentTracking) DeepCopyInto(out *IntentTracking) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntentTracking.
func (in *IntentTracking) DeepCopy() *IntentTracking {
	if in == nil {
		return nil
	}
	out := new(IntentTracking)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntentUsage) DeepCopyInto(out *IntentUsage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntentUsage.
func (in *IntentUsage) DeepCopy() *IntentUsage {
	if in == nil {
		return nil
	}
	out := new(IntentUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Investigation) DeepCopyInto(out *Investigation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Investigation.
func (in *Investigation) DeepCopy() *Investigation {
	if in == nil {
		return nil
	}
	out := new(Investigation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Investigation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvestigationList) DeepCopyInto(out *InvestigationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Investigation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvestigationList.
func (in *InvestigationList) DeepCopy() *InvestigationList {
	if in == nil {
		return nil
	}
	out := new(InvestigationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InvestigationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvestigationSpec) DeepCopyInto(out *InvestigationSpec) {
	*out = *in
	out.FindingRef = in.FindingRef
	if in.RepositoryRef != nil {
		in, out := &in.RepositoryRef, &out.RepositoryRef
		*out = new(LocalObjectReference)
		**out = **in
	}
	in.Parameters.DeepCopyInto(&out.Parameters)
	if in.PreviousAttempt != nil {
		in, out := &in.PreviousAttempt, &out.PreviousAttempt
		*out = new(PreviousAttempt)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvestigationSpec.
func (in *InvestigationSpec) DeepCopy() *InvestigationSpec {
	if in == nil {
		return nil
	}
	out := new(InvestigationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvestigationStatus) DeepCopyInto(out *InvestigationStatus) {
	*out = *in
	if in.JobRef != nil {
		in, out := &in.JobRef, &out.JobRef
		*out = new(JobReference)
		**out = **in
	}
	if in.RunnerImage != nil {
		in, out := &in.RunnerImage, &out.RunnerImage
		*out = new(RunnerImageRef)
		**out = **in
	}
	if in.Stage != nil {
		in, out := &in.Stage, &out.Stage
		*out = new(StageResult)
		(*in).DeepCopyInto(*out)
	}
	if in.Exploitability != nil {
		in, out := &in.Exploitability, &out.Exploitability
		*out = new(Analysis)
		**out = **in
	}
	if in.Likelihood != nil {
		in, out := &in.Likelihood, &out.Likelihood
		*out = new(Analysis)
		**out = **in
	}
	if in.Impact != nil {
		in, out := &in.Impact, &out.Impact
		*out = new(Analysis)
		**out = **in
	}
	if in.HoldReasons != nil {
		in, out := &in.HoldReasons, &out.HoldReasons
		*out = make([]HoldReason, len(*in))
		copy(*out, *in)
	}
	if in.RemediationParameters != nil {
		in, out := &in.RemediationParameters, &out.RemediationParameters
		*out = new(AgentParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvestigationStatus.
func (in *InvestigationStatus) DeepCopy() *InvestigationStatus {
	if in == nil {
		return nil
	}
	out := new(InvestigationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvestigationSummary) DeepCopyInto(out *InvestigationSummary) {
	*out = *in
	if in.HoldReasons != nil {
		in, out := &in.HoldReasons, &out.HoldReasons
		*out = make([]HoldReason, len(*in))
		copy(*out, *in)
	}
	if in.Estimate != nil {
		in, out := &in.Estimate, &out.Estimate
		*out = new(AgentEstimate)
		**out = **in
	}
	if in.RunnerImage != nil {
		in, out := &in.RunnerImage, &out.RunnerImage
		*out = new(RunnerImageRef)
		**out = **in
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvestigationSummary.
func (in *InvestigationSummary) DeepCopy() *InvestigationSummary {
	if in == nil {
		return nil
	}
	out := new(InvestigationSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobReference) DeepCopyInto(out *JobReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobReference.
func (in *JobReference) DeepCopy() *JobReference {
	if in == nil {
		return nil
	}
	out := new(JobReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalObjectReference) DeepCopyInto(out *LocalObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalObjectReference.
func (in *LocalObjectReference) DeepCopy() *LocalObjectReference {
	if in == nil {
		return nil
	}
	out := new(LocalObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalSecretReference) DeepCopyInto(out *LocalSecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalSecretReference.
func (in *LocalSecretReference) DeepCopy() *LocalSecretReference {
	if in == nil {
		return nil
	}
	out := new(LocalSecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Location) DeepCopyInto(out *Location) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Location.
func (in *Location) DeepCopy() *Location {
	if in == nil {
		return nil
	}
	out := new(Location)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonthlyBucket) DeepCopyInto(out *MonthlyBucket) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonthlyBucket.
func (in *MonthlyBucket) DeepCopy() *MonthlyBucket {
	if in == nil {
		return nil
	}
	out := new(MonthlyBucket)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectReference) DeepCopyInto(out *ObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectReference.
func (in *ObjectReference) DeepCopy() *ObjectReference {
	if in == nil {
		return nil
	}
	out := new(ObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PhaseTime) DeepCopyInto(out *PhaseTime) {
	*out = *in
	in.At.DeepCopyInto(&out.At)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PhaseTime.
func (in *PhaseTime) DeepCopy() *PhaseTime {
	if in == nil {
		return nil
	}
	out := new(PhaseTime)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreviousAttempt) DeepCopyInto(out *PreviousAttempt) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreviousAttempt.
func (in *PreviousAttempt) DeepCopy() *PreviousAttempt {
	if in == nil {
		return nil
	}
	out := new(PreviousAttempt)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Project) DeepCopyInto(out *Project) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Project.
func (in *Project) DeepCopy() *Project {
	if in == nil {
		return nil
	}
	out := new(Project)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Project) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectApprovers) DeepCopyInto(out *ProjectApprovers) {
	*out = *in
	if in.Logins != nil {
		in, out := &in.Logins, &out.Logins
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectApprovers.
func (in *ProjectApprovers) DeepCopy() *ProjectApprovers {
	if in == nil {
		return nil
	}
	out := new(ProjectApprovers)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectChecks) DeepCopyInto(out *ProjectChecks) {
	*out = *in
	if in.Fix != nil {
		in, out := &in.Fix, &out.Fix
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectChecks.
func (in *ProjectChecks) DeepCopy() *ProjectChecks {
	if in == nil {
		return nil
	}
	out := new(ProjectChecks)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectLabels) DeepCopyInto(out *ProjectLabels) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectLabels.
func (in *ProjectLabels) DeepCopy() *ProjectLabels {
	if in == nil {
		return nil
	}
	out := new(ProjectLabels)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectLimits) DeepCopyInto(out *ProjectLimits) {
	*out = *in
	if in.MaxRevisions != nil {
		in, out := &in.MaxRevisions, &out.MaxRevisions
		*out = new(int32)
		**out = **in
	}
	if in.MaxCheckFixes != nil {
		in, out := &in.MaxCheckFixes, &out.MaxCheckFixes
		*out = new(int32)
		**out = **in
	}
	out.Plan = in.Plan
	out.Build = in.Build
	out.Revise = in.Revise
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectLimits.
func (in *ProjectLimits) DeepCopy() *ProjectLimits {
	if in == nil {
		return nil
	}
	out := new(ProjectLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectList) DeepCopyInto(out *ProjectList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Project, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectList.
func (in *ProjectList) DeepCopy() *ProjectList {
	if in == nil {
		return nil
	}
	out := new(ProjectList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProjectList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectRepository) DeepCopyInto(out *ProjectRepository) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectRepository.
func (in *ProjectRepository) DeepCopy() *ProjectRepository {
	if in == nil {
		return nil
	}
	out := new(ProjectRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectSpec) DeepCopyInto(out *ProjectSpec) {
	*out = *in
	out.Labels = in.Labels
	in.Approvers.DeepCopyInto(&out.Approvers)
	if in.Repositories != nil {
		in, out := &in.Repositories, &out.Repositories
		*out = make([]ProjectRepository, len(*in))
		copy(*out, *in)
	}
	in.Limits.DeepCopyInto(&out.Limits)
	in.Checks.DeepCopyInto(&out.Checks)
	if in.RequireRepositoryImage != nil {
		in, out := &in.RequireRepositoryImage, &out.RequireRepositoryImage
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectSpec.
func (in *ProjectSpec) DeepCopy() *ProjectSpec {
	if in == nil {
		return nil
	}
	out := new(ProjectSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectStatus) DeepCopyInto(out *ProjectStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastPolledAt != nil {
		in, out := &in.LastPolledAt, &out.LastPolledAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectStatus.
func (in *ProjectStatus) DeepCopy() *ProjectStatus {
	if in == nil {
		return nil
	}
	out := new(ProjectStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyConfig) DeepCopyInto(out *ProxyConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyConfig.
func (in *ProxyConfig) DeepCopy() *ProxyConfig {
	if in == nil {
		return nil
	}
	out := new(ProxyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PullRequestRef) DeepCopyInto(out *PullRequestRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PullRequestRef.
func (in *PullRequestRef) DeepCopy() *PullRequestRef {
	if in == nil {
		return nil
	}
	out := new(PullRequestRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PullRequestStatus) DeepCopyInto(out *PullRequestStatus) {
	*out = *in
	if in.MergedAt != nil {
		in, out := &in.MergedAt, &out.MergedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PullRequestStatus.
func (in *PullRequestStatus) DeepCopy() *PullRequestStatus {
	if in == nil {
		return nil
	}
	out := new(PullRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimitStatus) DeepCopyInto(out *RateLimitStatus) {
	*out = *in
	if in.ResetAt != nil {
		in, out := &in.ResetAt, &out.ResetAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimitStatus.
func (in *RateLimitStatus) DeepCopy() *RateLimitStatus {
	if in == nil {
		return nil
	}
	out := new(RateLimitStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedeliveryStatus) DeepCopyInto(out *RedeliveryStatus) {
	*out = *in
	if in.LastSweepAt != nil {
		in, out := &in.LastSweepAt, &out.LastSweepAt
		*out = (*in).DeepCopy()
	}
	if in.ReplayedAt != nil {
		in, out := &in.ReplayedAt, &out.ReplayedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedeliveryStatus.
func (in *RedeliveryStatus) DeepCopy() *RedeliveryStatus {
	if in == nil {
		return nil
	}
	out := new(RedeliveryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RelatedFinding) DeepCopyInto(out *RelatedFinding) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RelatedFinding.
func (in *RelatedFinding) DeepCopy() *RelatedFinding {
	if in == nil {
		return nil
	}
	out := new(RelatedFinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Remediation) DeepCopyInto(out *Remediation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Remediation.
func (in *Remediation) DeepCopy() *Remediation {
	if in == nil {
		return nil
	}
	out := new(Remediation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Remediation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationList) DeepCopyInto(out *RemediationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Remediation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationList.
func (in *RemediationList) DeepCopy() *RemediationList {
	if in == nil {
		return nil
	}
	out := new(RemediationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RemediationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationSpec) DeepCopyInto(out *RemediationSpec) {
	*out = *in
	out.FindingRef = in.FindingRef
	out.InvestigationRef = in.InvestigationRef
	out.RepositoryRef = in.RepositoryRef
	in.Parameters.DeepCopyInto(&out.Parameters)
	if in.PreviousAttempt != nil {
		in, out := &in.PreviousAttempt, &out.PreviousAttempt
		*out = new(PreviousAttempt)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationSpec.
func (in *RemediationSpec) DeepCopy() *RemediationSpec {
	if in == nil {
		return nil
	}
	out := new(RemediationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationStatus) DeepCopyInto(out *RemediationStatus) {
	*out = *in
	if in.GrantedAt != nil {
		in, out := &in.GrantedAt, &out.GrantedAt
		*out = (*in).DeepCopy()
	}
	if in.JobRef != nil {
		in, out := &in.JobRef, &out.JobRef
		*out = new(JobReference)
		**out = **in
	}
	if in.RunnerImage != nil {
		in, out := &in.RunnerImage, &out.RunnerImage
		*out = new(RunnerImageRef)
		**out = **in
	}
	if in.Stage != nil {
		in, out := &in.Stage, &out.Stage
		*out = new(StageResult)
		(*in).DeepCopyInto(*out)
	}
	if in.PullRequest != nil {
		in, out := &in.PullRequest, &out.PullRequest
		*out = new(PullRequestRef)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationStatus.
func (in *RemediationStatus) DeepCopy() *RemediationStatus {
	if in == nil {
		return nil
	}
	out := new(RemediationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationSummary) DeepCopyInto(out *RemediationSummary) {
	*out = *in
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationSummary.
func (in *RemediationSummary) DeepCopy() *RemediationSummary {
	if in == nil {
		return nil
	}
	out := new(RemediationSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Repository) DeepCopyInto(out *Repository) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Repository.
func (in *Repository) DeepCopy() *Repository {
	if in == nil {
		return nil
	}
	out := new(Repository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Repository) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryList) DeepCopyInto(out *RepositoryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Repository, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryList.
func (in *RepositoryList) DeepCopy() *RepositoryList {
	if in == nil {
		return nil
	}
	out := new(RepositoryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RepositoryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryRef) DeepCopyInto(out *RepositoryRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryRef.
func (in *RepositoryRef) DeepCopy() *RepositoryRef {
	if in == nil {
		return nil
	}
	out := new(RepositoryRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositorySpec) DeepCopyInto(out *RepositorySpec) {
	*out = *in
	out.Ref = in.Ref
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositorySpec.
func (in *RepositorySpec) DeepCopy() *RepositorySpec {
	if in == nil {
		return nil
	}
	out := new(RepositorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryStatus) DeepCopyInto(out *RepositoryStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Forge != nil {
		in, out := &in.Forge, &out.Forge
		*out = new(LocalObjectReference)
		**out = **in
	}
	if in.Artifact != nil {
		in, out := &in.Artifact, &out.Artifact
		*out = new(Artifact)
		(*in).DeepCopyInto(*out)
	}
	if in.RunnerImage != nil {
		in, out := &in.RunnerImage, &out.RunnerImage
		*out = new(RunnerImage)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryStatus.
func (in *RepositoryStatus) DeepCopy() *RepositoryStatus {
	if in == nil {
		return nil
	}
	out := new(RepositoryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RollupBucket) DeepCopyInto(out *RollupBucket) {
	*out = *in
	if in.Phases != nil {
		in, out := &in.Phases, &out.Phases
		*out = make(map[string]int64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Recommendations != nil {
		in, out := &in.Recommendations, &out.Recommendations
		*out = make(map[string]int64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Stages != nil {
		in, out := &in.Stages, &out.Stages
		*out = make(map[string]StageAggregate, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RollupBucket.
func (in *RollupBucket) DeepCopy() *RollupBucket {
	if in == nil {
		return nil
	}
	out := new(RollupBucket)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RollupScope) DeepCopyInto(out *RollupScope) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RollupScope.
func (in *RollupScope) DeepCopy() *RollupScope {
	if in == nil {
		return nil
	}
	out := new(RollupScope)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerImage) DeepCopyInto(out *RunnerImage) {
	*out = *in
	if in.ResolvedAt != nil {
		in, out := &in.ResolvedAt, &out.ResolvedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerImage.
func (in *RunnerImage) DeepCopy() *RunnerImage {
	if in == nil {
		return nil
	}
	out := new(RunnerImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerImageRef) DeepCopyInto(out *RunnerImageRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerImageRef.
func (in *RunnerImageRef) DeepCopy() *RunnerImageRef {
	if in == nil {
		return nil
	}
	out := new(RunnerImageRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StageAggregate) DeepCopyInto(out *StageAggregate) {
	*out = *in
	if in.Outcomes != nil {
		in, out := &in.Outcomes, &out.Outcomes
		*out = make(map[string]int64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Estimate != nil {
		in, out := &in.Estimate, &out.Estimate
		*out = new(EstimateAggregate)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StageAggregate.
func (in *StageAggregate) DeepCopy() *StageAggregate {
	if in == nil {
		return nil
	}
	out := new(StageAggregate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StageLimits) DeepCopyInto(out *StageLimits) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StageLimits.
func (in *StageLimits) DeepCopy() *StageLimits {
	if in == nil {
		return nil
	}
	out := new(StageLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StageResult) DeepCopyInto(out *StageResult) {
	*out = *in
	out.Usage = in.Usage
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.FinishedAt != nil {
		in, out := &in.FinishedAt, &out.FinishedAt
		*out = (*in).DeepCopy()
	}
	if in.Transcript != nil {
		in, out := &in.Transcript, &out.Transcript
		*out = new(TranscriptRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StageResult.
func (in *StageResult) DeepCopy() *StageResult {
	if in == nil {
		return nil
	}
	out := new(StageResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StaleObservation) DeepCopyInto(out *StaleObservation) {
	*out = *in
	in.ObservedAt.DeepCopyInto(&out.ObservedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StaleObservation.
func (in *StaleObservation) DeepCopy() *StaleObservation {
	if in == nil {
		return nil
	}
	out := new(StaleObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrackedComment) DeepCopyInto(out *TrackedComment) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrackedComment.
func (in *TrackedComment) DeepCopy() *TrackedComment {
	if in == nil {
		return nil
	}
	out := new(TrackedComment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrackingStatus) DeepCopyInto(out *TrackingStatus) {
	*out = *in
	if in.Comments != nil {
		in, out := &in.Comments, &out.Comments
		*out = make([]TrackedComment, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrackingStatus.
func (in *TrackingStatus) DeepCopy() *TrackingStatus {
	if in == nil {
		return nil
	}
	out := new(TrackingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TranscriptRef) DeepCopyInto(out *TranscriptRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TranscriptRef.
func (in *TranscriptRef) DeepCopy() *TranscriptRef {
	if in == nil {
		return nil
	}
	out := new(TranscriptRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnitPlan) DeepCopyInto(out *UnitPlan) {
	*out = *in
	if in.Harnesses != nil {
		in, out := &in.Harnesses, &out.Harnesses
		*out = make([]HarnessOption, len(*in))
		copy(*out, *in)
	}
	out.Workspace = in.Workspace
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnitPlan.
func (in *UnitPlan) DeepCopy() *UnitPlan {
	if in == nil {
		return nil
	}
	out := new(UnitPlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UsageSummary) DeepCopyInto(out *UsageSummary) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UsageSummary.
func (in *UsageSummary) DeepCopy() *UsageSummary {
	if in == nil {
		return nil
	}
	out := new(UsageSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WizAPI) DeepCopyInto(out *WizAPI) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WizAPI.
func (in *WizAPI) DeepCopy() *WizAPI {
	if in == nil {
		return nil
	}
	out := new(WizAPI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WizDefend) DeepCopyInto(out *WizDefend) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WizDefend.
func (in *WizDefend) DeepCopy() *WizDefend {
	if in == nil {
		return nil
	}
	out := new(WizDefend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WizIntegration) DeepCopyInto(out *WizIntegration) {
	*out = *in
	if in.Issues != nil {
		in, out := &in.Issues, &out.Issues
		*out = new(WizIssues)
		**out = **in
	}
	if in.Defend != nil {
		in, out := &in.Defend, &out.Defend
		*out = new(WizDefend)
		**out = **in
	}
	if in.API != nil {
		in, out := &in.API, &out.API
		*out = new(WizAPI)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WizIntegration.
func (in *WizIntegration) DeepCopy() *WizIntegration {
	if in == nil {
		return nil
	}
	out := new(WizIntegration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WizIssues) DeepCopyInto(out *WizIssues) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WizIssues.
func (in *WizIssues) DeepCopy() *WizIssues {
	if in == nil {
		return nil
	}
	out := new(WizIssues)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceRef) DeepCopyInto(out *WorkspaceRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceRef.
func (in *WorkspaceRef) DeepCopy() *WorkspaceRef {
	if in == nil {
		return nil
	}
	out := new(WorkspaceRef)
	in.DeepCopyInto(out)
	return out
}
