{{/*
Copyright 2026 Bitwise Media Group Ltd.
SPDX-License-Identifier: MIT

The preview sign-in relay's derived state, computed ONCE per render and shared
by every template that needs it (preview-auth.yaml, preview-admission.yaml,
preview-foundation.yaml, configmap.yaml, NOTES.txt). Generating keys draws
randomness, so a second computation would disagree with the first: the result
is memoised as JSON on .Values.previewAuth._state, which every template of one
render shares. Callers read it with
    $st := include "patchy.previewAuthState" . | fromJson
(fromJson makes every number a float64: int it before use).

Fields:
  enabled            previewAuth.enabled
  stage              permit | require
  issuer             https://<host>
  managedKeys        the chart owns the keys Secret (no keys.existingSecret)
  keysSecret         the keys Secret's name
  keys               managedKeys only: the Secret's data, base64
  keysFresh          managedKeys only: generated by this render
  gen, prevGen       the current and previous key generation (0: none)
  admits             the generations the slot Ingress policy admits ("g1,g2")
  sets               generation -> slot namespace -> its six pinned
                     annotations (every value a string)
  clientSecrets      managedKeys only: generation -> slot -> client secret
  applyGen           require only: the generation the controller and the
                     placeholder put on slot Ingresses
  otherGen           require only: the other admitted generation, or 0

A slot's pinned set for generation g:
  alb.ingress.kubernetes.io/auth-type                 oidc
  alb.ingress.kubernetes.io/auth-idp-oidc             {"authorizationEndpoint":"<issuer>/authorize","issuer":"<issuer>",
                                                       "secretName":"patchy-preview-oidc-g<g>",
                                                       "tokenEndpoint":"<issuer>/token","userInfoEndpoint":"<issuer>/userinfo"}
  alb.ingress.kubernetes.io/auth-on-unauthenticated-request  authenticate
  alb.ingress.kubernetes.io/auth-scope                openid
  alb.ingress.kubernetes.io/auth-session-cookie       patchy-preview-s<slot>
  alb.ingress.kubernetes.io/auth-session-timeout      <sessionTimeout>
rendered once here, so the controller (PATCHY_PREVIEW_AUTH_ANNOTATIONS), the
placeholder and both admission policies carry the very same bytes.

A slot's ALB client secret is hex(sha256(master || "\x00patchy-preview-auth/
v1/client-secret\x00" || generation || "\x00" || slot)), the construction
internal/previewauth reproduces (a Go test renders the chart and compares).
*/}}
{{- define "patchy.previewAuthState" -}}
{{- $pa := .Values.previewAuth -}}
{{- if not (hasKey $pa "_state") -}}
{{- $st := dict "enabled" false -}}
{{- if $pa.enabled -}}
{{- $p := .Values.preview -}}
{{- $fullname := include "patchy.fullname" . -}}
{{- $ns := .Release.Namespace -}}
{{- if not $p.enabled }}{{ fail "previewAuth.enabled requires preview.enabled: it signs viewers in to the preview slots" }}{{ end -}}
{{- if not $pa.host }}{{ fail "previewAuth.host is required when previewAuth.enabled: the relay's public hostname, its issuer https://<host>" }}{{ end -}}
{{- if or (eq $pa.host $p.hostSuffix) (hasSuffix (printf ".%s" $p.hostSuffix) $pa.host) }}{{ fail (printf "previewAuth.host %s must not be under preview.hostSuffix %s: the preview wildcard would route it to the preview ALB" $pa.host $p.hostSuffix) }}{{ end -}}
{{- if not $pa.dex.issuerURL }}{{ fail "previewAuth.dex.issuerURL is required when previewAuth.enabled" }}{{ end -}}
{{- if not $pa.dex.clientID }}{{ fail "previewAuth.dex.clientID is required when previewAuth.enabled" }}{{ end -}}
{{- if not $pa.dex.existingSecret }}{{ fail "previewAuth.dex.existingSecret is required when previewAuth.enabled: a Secret holding the relay's Dex client secret" }}{{ end -}}
{{- if or (not $pa.claims.usernamePrefix) (not $pa.claims.groupsPrefix) }}{{ fail "previewAuth.claims.usernamePrefix and groupsPrefix are required" }}{{ end -}}
{{- if and (eq $pa.stage "require") (not .Values.previewController.enabled) }}{{ fail "previewAuth.stage require needs previewController.enabled: it puts every preview Ingress behind sign-in" }}{{ end -}}
{{- $issuer := printf "https://%s" $pa.host -}}
{{- $keysSecret := $pa.keys.existingSecret | default (printf "%s-preview-auth-keys" $fullname) -}}
{{- $managed := not $pa.keys.existingSecret -}}
{{- $gen := 0 -}}
{{- $prevGen := 0 -}}
{{- $keys := dict -}}
{{- $masters := dict -}}
{{- $fresh := false -}}
{{- if $managed -}}
{{- $live := lookup "v1" "Secret" $ns $keysSecret -}}
{{- $data := (get $live "data") | default dict -}}
{{- if and (hasKey $data "master") (hasKey $data "generation") (hasKey $data "signingKey") -}}
{{- $gen = atoi (b64dec $data.generation) -}}
{{- $_ := set $keys "master" $data.master -}}
{{- $_ := set $keys "generation" $data.generation -}}
{{- $_ := set $keys "signingKey" $data.signingKey -}}
{{- if and (hasKey $data "previousMaster") (hasKey $data "previousGeneration") -}}
{{- $prevGen = atoi (b64dec $data.previousGeneration) -}}
{{- $_ := set $keys "previousMaster" $data.previousMaster -}}
{{- $_ := set $keys "previousGeneration" $data.previousGeneration -}}
{{- with $data.previousSigningKey }}{{ $_ := set $keys "previousSigningKey" . }}{{ end -}}
{{- end -}}
{{- else -}}
{{- /* No keys Secret. A release that generated one before records its
       generation on the relay ConfigMap: refuse to replace lost keys
       silently (every session ends, and the slot client Secrets would
       change under live Ingresses). */ -}}
{{- $cm := lookup "v1" "ConfigMap" $ns (printf "%s-preview-auth-config" $fullname) -}}
{{- $marker := dig "metadata" "annotations" "patchy.bitwisemedia.uk/preview-auth-key-generation" "" $cm -}}
{{- if and $marker (not $pa.keys.regenerate) }}{{ fail (printf "the keys Secret %s is missing, but this release generated generation %s before: restore it, or set previewAuth.keys.regenerate=true to generate new keys (it signs everyone out, and the new generation needs the permit stage again)" $keysSecret $marker) }}{{ end -}}
{{- $gen = max 1 (int $pa.keys.rotate) (add (atoi ($marker | default "0")) 1) | int -}}
{{- $_ := set $keys "master" (randAlphaNum 64 | b64enc) -}}
{{- $_ := set $keys "generation" (toString $gen | b64enc) -}}
{{- $_ := set $keys "signingKey" (genPrivateKey "rsa" | b64enc) -}}
{{- $fresh = true -}}
{{- end -}}
{{- if and (not $fresh) (gt (int $pa.keys.rotate) $gen) -}}
{{- /* Rotate: the current keys become the previous ones; a previous
       generation from an earlier rotation is dropped. */ -}}
{{- $_ := set $keys "previousMaster" $keys.master -}}
{{- $_ := set $keys "previousGeneration" $keys.generation -}}
{{- $_ := set $keys "previousSigningKey" $keys.signingKey -}}
{{- $prevGen = $gen -}}
{{- $gen = int $pa.keys.rotate -}}
{{- $_ := set $keys "master" (randAlphaNum 64 | b64enc) -}}
{{- $_ := set $keys "generation" (toString $gen | b64enc) -}}
{{- $_ := set $keys "signingKey" (genPrivateKey "rsa" | b64enc) -}}
{{- else if and $pa.keys.dropPrevious (gt $prevGen 0) -}}
{{- $_ := unset $keys "previousMaster" -}}
{{- $_ := unset $keys "previousGeneration" -}}
{{- $_ := unset $keys "previousSigningKey" -}}
{{- $prevGen = 0 -}}
{{- end -}}
{{- $_ := set $masters (toString $gen) (b64dec $keys.master) -}}
{{- if gt $prevGen 0 }}{{ $_ := set $masters (toString $prevGen) (b64dec $keys.previousMaster) }}{{ end -}}
{{- else -}}
{{- $gen = int $pa.keys.generation -}}
{{- $prevGen = int $pa.keys.previousGeneration -}}
{{- if eq $gen $prevGen }}{{ fail "previewAuth.keys.previousGeneration must differ from keys.generation" }}{{ end -}}
{{- end -}}
{{- $gens := list $gen -}}
{{- if gt $prevGen 0 }}{{ $gens = append $gens $prevGen }}{{ end -}}
{{- $admits := list -}}
{{- range $g := $gens | sortAlpha }}{{ $admits = append $admits (printf "g%v" $g) }}{{ end -}}
{{- $sets := dict -}}
{{- $clientSecrets := dict -}}
{{- range $g := $gens -}}
{{- $idp := dict "issuer" $issuer "authorizationEndpoint" (printf "%s/authorize" $issuer) "tokenEndpoint" (printf "%s/token" $issuer) "userInfoEndpoint" (printf "%s/userinfo" $issuer) "secretName" (printf "patchy-preview-oidc-g%d" $g) | toJson -}}
{{- $byNS := dict -}}
{{- $secrets := dict -}}
{{- range $i := until (int $p.slotCount) -}}
{{- $_ := set $byNS (printf "patchy-preview-%d" $i) (dict
    "alb.ingress.kubernetes.io/auth-type" "oidc"
    "alb.ingress.kubernetes.io/auth-idp-oidc" $idp
    "alb.ingress.kubernetes.io/auth-on-unauthenticated-request" "authenticate"
    "alb.ingress.kubernetes.io/auth-scope" "openid"
    "alb.ingress.kubernetes.io/auth-session-cookie" (printf "patchy-preview-s%d" $i)
    "alb.ingress.kubernetes.io/auth-session-timeout" (toString (int $pa.sessionTimeout))) -}}
{{- if $managed -}}
{{- $_ := set $secrets (toString $i) (sha256sum (printf "%s\x00patchy-preview-auth/v1/client-secret\x00%d\x00%d" (get $masters (toString $g)) $g $i)) -}}
{{- end -}}
{{- end -}}
{{- $_ := set $sets (toString $g) $byNS -}}
{{- if $managed }}{{ $_ := set $clientSecrets (toString $g) $secrets }}{{ end -}}
{{- end -}}
{{- $applyGen := 0 -}}
{{- $otherGen := 0 -}}
{{- if eq $pa.stage "require" -}}
{{- /* The require stage applies a generation only once the live slot
       Ingress policy admits it (the permit stage's marker), or the operator
       confirms it for a render that cannot look: Helm updates the placeholder
       Ingress, and the controller patches every slot Ingress, before it
       updates any admission policy. A rotation's first upgrade therefore
       keeps applying the previous generation; the next applies the new. */ -}}
{{- $vap := lookup "admissionregistration.k8s.io/v1" "ValidatingAdmissionPolicy" "" "patchy-preview-ingresses" -}}
{{- $live := splitList "," (dig "metadata" "annotations" "patchy.bitwisemedia.uk/preview-auth-admits" "" $vap) -}}
{{- $confirmed := int ($pa.permitConfirmedGeneration | default 0) -}}
{{- if or (has (printf "g%d" $gen) $live) (eq $confirmed $gen) -}}
{{- $applyGen = $gen -}}
{{- $otherGen = $prevGen -}}
{{- else if and (gt $prevGen 0) (or (has (printf "g%d" $prevGen) $live) (eq $confirmed $prevGen)) -}}
{{- $applyGen = $prevGen -}}
{{- $otherGen = $gen -}}
{{- else -}}
{{- fail (printf "previewAuth.stage require: the live slot Ingress policy patchy-preview-ingresses does not admit key generation %d yet (it admits %q). Upgrade once with previewAuth.stage=permit first; a render without a cluster (helm template, GitOps) sets previewAuth.permitConfirmedGeneration=%d once that permit stage is live" $gen (join "," $live) $gen) -}}
{{- end -}}
{{- end -}}
{{- $st = dict "enabled" true "stage" $pa.stage "issuer" $issuer "managedKeys" $managed "keysSecret" $keysSecret
    "keys" $keys "keysFresh" $fresh "gen" $gen "prevGen" $prevGen "admits" (join "," $admits) "sets" $sets
    "clientSecrets" $clientSecrets "applyGen" $applyGen "otherGen" $otherGen -}}
{{- end -}}
{{- $_ := set $pa "_state" ($st | toJson) -}}
{{- end -}}
{{- get $pa "_state" -}}
{{- end }}

{{/*
The admission rules' view of the pinned sets: slot namespace -> the list of
sets admitted there (one per admitted generation), as a JSON literal CEL reads
as a map. Context: the state from patchy.previewAuthState; .gens is a list of
generations.
*/}}
{{- define "patchy.previewAuthWant" -}}
{{- $out := dict -}}
{{- range $g := .gens -}}
{{- range $ns, $set := get $.st.sets (toString (int $g)) -}}
{{- $_ := set $out $ns (append (get $out $ns | default list) $set) -}}
{{- end -}}
{{- end -}}
{{- $out | toJson -}}
{{- end }}
